#!/usr/bin/env node
console.log("arguments ", process.argv)
var odd = process.argv.pop();
console.log("what is the number ", odd);

if(1 == odd % 2 ) {
    console.log("this is odd number");
} else {
    console.log("this is even number");
}
